---
- include_tasks: priv_install.yml

- include_tasks: suse.yml
  when: ansible_distribution in ["openSUSE Tumbleweed"]

- include_tasks: ssh_install.yml

- include_tasks: user_creation.yml
  when: NEW_USERS is defined

- include_tasks: auth.yml