- name: Change OpenSSH Package Name (SUSE)
  set_fact: SSH_SERVER_PACKAGE="openssh"
  when: ansible_os_family in ["Suse"]

- name: Install packages
  package:
    name:
      - "{{ SSH_SERVER_PACKAGE }}"
      - sudo
    state: present
